bluesquare_notifications_bundle_notifications_get:
    path:     /get
    controller: Bluesquare\NotificationsBundle\Controller\MainController::getAll
    methods: [GET]

bluesquare_notifications_bundle_notifications_delete:
    path:     /delete/{id}
    controller: Bluesquare\NotificationsBundle\Controller\MainController::delete
    methods: [DELETE]
    requirements:
        id: '\d+'

bluesquare_notifications_bundle_notifications_mark_seen:
    path:     /mark-seen/{id}
    controller: Bluesquare\NotificationsBundle\Controller\MainController::markSeen
    methods: [POST]
    requirements:
        id: '\d+'
