services:
  # Si on a des repositories...
  Bluesquare\NotificationsBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    tags: ['doctrine.repository_service']

  # Services : alias
  Bluesquare\NotificationsBundle\Service\NotificationsService: '@bluesquare.notifications_bundle.notifssrv'

  # Services : params
  bluesquare.notifications_bundle.notifssrv:
    class: Bluesquare\NotificationsBundle\Service\NotificationsService
    autowire: true
    public: true
    arguments: ['@doctrine.orm.entity_manager']